server.port=8080
server.address=0.0.0.0

spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB

alpr.files.dir=./files
alpr.thumbs.dir=${alpr.output.dir}/thumbs

alpr.python.bin=/Users/wenze/Developer/LicensePlateRecognition/.venv/bin/python3
alpr.project.root=/Users/wenze/Developer/LicensePlateRecognition
alpr.assets.dir=/Users/wenze/Developer/LicensePlateRecognition/assets
alpr.output.dir=/Users/wenze/alpr_outputs

# MySQL ??
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/parking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=zhanga614371734Z

# ?? JPA ?????Flyway ????????
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false

# ??? UTC ??????????
spring.jackson.time-zone=UTC

# ?????
logging.level.com.wenze.alpr=DEBUG
management.endpoints.web.exposure.include=health,info,mappings
